### ISSUE TITLE
a question about footbook

### ISSUE THREAD

**Issue by rebirthwyw** [david942j/ctf-writeups#1]
```
do port forwarding and use http://127.0.0.1:3000 for connection
```
does it mean:I bind my local port 3000 to request this service？？？
I see the js use "location.host" to judge
and the OAuth of dropbox can't use http unless host is local
so should use a vulnerability to proxy？？？

**Comment by david942j** [comment]
Yes, bind your local port 3000 to request the web service
A simple command to do this is: (tested on Ubuntu)
`ncat -vkl 127.0.0.1 3000 -c 'nc 13.114.238.13 80'`

Sorry but I don't understand what do you mean ''a vulnerability of proxy''

Since OAuth needs set the valid callback url, and I set it as `http://127.0.0.1:3000`, so you need to proxy the service to 'cheat' the OAuth providers you're using localhost for connection

**Comment by rebirthwyw** [comment]
you mean I bind my local port 3000 to request the OAuth
```
https://www.dropbox.com/oauth2/authorize?client_id=rv1p9ptdvbyrn2d&redirect_uri=http%3A%2F%2F13.114.238.13%2Fauth%2Fdropbox_oauth2%2Fcallback&response_type=code&state=1296612bc8c262f2912131b43818821e5ee55d9730eb650c
```
like this???

**Comment by david942j** [comment]
Nope, only need bind 3000 to request Footbook (the ip I provided above is the service ip during hitcon ctf)

**Comment by rebirthwyw** [comment]
thx for your reply,I have solved it.And when will https://ctf2017.hitcon.org close???

**Comment by david942j** [comment]
The scoreboard will remain there, but services will be closed today
